name: movies_api
description: A movies api package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^2.4.0

flutter:
